# Generated by Django 6.1 on 2026-08-27 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=20, unique=True)),
                ('floor', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('occupied', models.IntegerField(default=0)),
                ('room_type', models.CharField(max_length=50)),
                ('status', models.CharField(default='Available', max_length=50)),
            ],
        ),
    ]
